### ISSUE TITLE
Fails if $HOME/.mycroft doesn't exist

### ISSUE THREAD

**Issue by forslund** [MycroftAI/mycroft-skills-manager#62]
Currently the saving of skills.json doesn't validate that the folder `~/.mycroft` folder exists.

The [write_skill_state()](https://github.com/MycroftAI/mycroft-skills-manager/blob/master/msm/skill_state.py#L24) function should validate that the directory exists and try to create it if it doesn't.

**Comment by luca-vercelli** [comment]
Sorry, I don't understand if this issue should be solved or not. I don't think so. The fix has not been accepted?

**Comment by forslund** [comment]
Hi, #63 was closed by the creator. So it's currently not solved
